### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by hengjiUSTC** [steamship-packages/langchain-production-starter#4]
Got following error running deploy.
```
langchain-agent-production-starter   main ?  python3 deploy.py                                                                               ✔  7361  12:58:13
Steamship Python CLI version 2.16.10rc1
What handle would you like to use for your package? Valid characters are a-z and -: test-demo
Creating / fetching package with handle [test-demo]... Done.
Bundling content... Done. 📦
What should the new version be? Valid characters are a-z, 0-9, . and - [1.0.0]: 
Deploying version 1.0.0 of [test-demo]... 🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢
Unable to deploy package version.
Server returned message: There was an error loading the main file (it must be named api.py):
Traceback (most recent call last):
  File "/var/task/steamship/invocable/lambda_handler.py", line 285, in safely_find_invocable_class
    module = importlib.import_module("api")
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/api.py", line 4, in <module>
    from langchain.agents import Tool, initialize_agent, AgentType, AgentExecutor
  File "/var/task/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/var/task/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/var/task/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.tools import InvalidTool
  File "/var/task/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/var/task/langchain/tools/__init__.py", line 40, in <module>
    from langchain.tools.vectorstore.tool import (
  File "/var/task/langchain/tools/vectorstore/tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "/var/task/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/var/task/langchain/chains/api/base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/var/task/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/var/task/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/var/task/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/var/task/langchain/memory/__init__.py", line 25, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/var/task/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/var/task/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/var/task/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/var/task/langchain/embeddings/__init__.py", line 19, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/var/task/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
    fields[ann_name] = ModelField.infer(
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
    return cls(
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
    self.prepare()
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
    self._type_analysis()
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
    return self.__class__(
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
    self.prepare()
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
    self._type_analysis()
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
    elif issubclass(origin, Tuple):  # type: ignore
  File "/var/lang/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Aborted!
bot_token:
```

**Comment by EniasCailliau** [comment]
Thanks for reporting, looking into it now!

**Comment by EniasCailliau** [comment]
Looks like LangChain introduced a new version that isn't backward compatible. Updated requirements.txt to fix the dependency. 

Could you try again and let me know if that works for you?

**Comment by hengjiUSTC** [comment]
still getting error.
```
langchain-agent-production-starter   main ● ?  python3 deploy.py
Steamship Python CLI version 2.16.10rc1
Creating / fetching package with handle [test-demo]... Done.
Bundling content... Done. 📦
Deploying version 1.0.0 of [test-demo]... 🚢🚢🚢🚢
It looks like that version [1.0.0] has already been deployed. Would you like to change the version handle and try again? [Y/n]: y
What should the new version be? Valid characters are a-z, 0-9, . and - [1.0.0-rc.1]: 2.0.0
Deploying version 2.0.0 of [test-demo]... 🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢
Unable to deploy package version.
Server returned message: There was an error loading the main file (it must be named api.py):
Traceback (most recent call last):
  File "/var/task/steamship/invocable/lambda_handler.py", line 285, in safely_find_invocable_class
    module = importlib.import_module("api")
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/api.py", line 4, in <module>
    from langchain.agents import Tool, initialize_agent, AgentType, AgentExecutor
  File "/var/task/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/var/task/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/var/task/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.tools import InvalidTool
  File "/var/task/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/var/task/langchain/tools/__init__.py", line 40, in <module>
    from langchain.tools.vectorstore.tool import (
  File "/var/task/langchain/tools/vectorstore/tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "/var/task/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/var/task/langchain/chains/api/base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/var/task/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/var/task/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/var/task/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/var/task/langchain/memory/__init__.py", line 25, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/var/task/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/var/task/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/var/task/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/var/task/langchain/embeddings/__init__.py", line 19, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/var/task/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
    fields[ann_name] = ModelField.infer(
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
    return cls(
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
    self.prepare()
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
    self._type_analysis()
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
    return self.__class__(
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
    self.prepare()
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
    self._type_analysis()
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
    elif issubclass(origin, Tuple):  # type: ignore
  File "/var/lang/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Aborted!
```
I didn't see main branch's requirements.txt been update? did you pushed?

**Comment by ghost** [comment]
yes I have the same error

**Comment by ghost** [comment]
I believe this is now fixed but there as an error with the ElevenLabs API. The bot is able to deploy to Telegram but when a message is sent from Eleven Labs: Unauthorized.
